TomasMallar/ProyectoFinalHenry

api/package.json
api/src/controllers/ProductsController.js
api/src/db.js
api/src/handlers/ProductsHandler.js
api/src/models/CategoriesMode.js
api/src/models/ProductsModel.js
api/src/models/UserModel.js
api/src/routes/ProductsRouter/ProductsRouter.js
api/src/routes/index.js

Estructuración del backend (creación de las carpetas routes, handlers y controllers).
Creacion de los modelos con sus respectivas validaciones, relacion de muchos a muchos entre la tabla PRODUCTS (chocolates) y la tabla CATEGORIAS (faltaria la relacion con usuario) 
y por ultimo cree la ruta getAllProducts que trae todos los chocolates de la DB (NO trae todo de la DB)

Estructura, Modelos, getAllProducts

---

client/src/Components/Button.jsx
client/src/Pages/Home.jsx

Created both folders for containing components and Pages. In each folder I added the first element, a button and the homepage.

Front end components

---

client/src/components/NavBar.jsx

Agregué el componente NavBar a la carpeta components

Prueba de creacion NavBar

---

api/src/controllers/categoriesController/CategoriesController.js
api/src/handlers/categoriesHandle/CategoriesHandler.js
api/src/models/CategoriesModel.js
api/src/models/IngredientsModel.js
api/src/models/TypesModel.js
api/src/routes/CategoryRouter/CategoryRouter.js

agregue la ruta para eliminar y actualizar categorias

route-categories-delete&update

---

api/src/controllers/productsController/GetProductByNameController.js
api/src/controllers/productsController/deleteProductController.js
api/src/controllers/productsController/getProductByIdController.js
api/src/controllers/productsController/getProductsAll.js
api/src/controllers/productsController/postProductController.js
api/src/controllers/productsController/updateProductController.js
api/src/handlers/productsHandle/deleteProductHandler.js
api/src/handlers/productsHandle/getProductByIdHandler.js
api/src/handlers/productsHandle/getProductsHandler.js
api/src/handlers/productsHandle/postProductHandler.js
api/src/handlers/productsHandle/updateProductHandler.js
api/src/helpers/cleanArrayProduct.js
api/src/models/ProductsModel.js
api/src/routes/ProductsRouter/ProductsRouter.js

Chicos, son las mismas Rutas, Handlers, Controllers, etc para Product, revisen si tienen conflictos con los archivos asi los completo con las orbaservaciones que habian comentado en la anterior rama, disculpen que sea un solo commit, no llegamos con el tiempo si no.

New   backend    product crud

---

api/src/db.js
api/src/middlewares/validateCategories/validatePostCategory.js
api/src/middlewares/validateCategories/validatePutCategory.js
api/src/middlewares/validateProducts/validatePostProduct.js
api/src/middlewares/validateProducts/validatePutProduct.js
api/src/middlewares/validateUser/validatePostUser.js
api/src/models/RolModel.js
api/src/routes/CategoryRouter/CategoryRouter.js
api/src/routes/ProductsRouter/ProductsRouter.js

agregue los middlewares para validar que todos los datos lleguen a usuario, product y category

add Middlewares y relaciones de los modelos

---

client/src/App.js
client/src/Components/ProductCard/ProductCard.jsx
client/src/Components/ProductCard/card.module.css
client/src/Pages/DataManagement.jsx
client/src/Pages/Home.jsx
client/src/Redux/Actions/Actions.js
client/src/Redux/Reducer/Reducer.js
client/src/Redux/Store/Store.js
client/src/index.js

Se agregó la tarjeta de producto como componente,
Se mapearon en el home las tarjetas con todos los productos Se linkeó el backend con el frontend de manera local

trae los datos del backend. Creacion de Data Management, Cards, Home

---

client/src/Pages/NewUser/NewUser.jsx
client/src/Pages/NewUser/NewUser.module.css
client/src/Pages/NewUser/validations.js
package.json

Validaciones del formulario Create new user, deje comentado el dispatch del post hasta que tengamos en funcionamiento las rutas y conexión con el Back Manejo de errores en el formulario

Formulario Create New User

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Components/Footer/Footer.module.css
client/src/Components/ProductCard/card.module.css
client/src/Pages/DataManagement.jsx
client/src/Pages/Home.jsx
client/src/Pages/detail/detail.jsx
client/src/Pages/detail/detail.module.css
client/src/Redux/Actions/Actions.js

Agregado de componente Detail.
Correccion de estilos en tags genericos que afectaban a toda la página.

Detail + correcciones de formato generales

---

api/src/controllers/productsController/GetProductByNameController.js

Correccion de GetProductByName

---

client/src/Pages/Home.jsx
client/src/Pages/NewUser/NewUser.module.css
client/src/Pages/sortingAndFiltering/sortingAndFiltering.jsx

SearchBar en el archivo sorting and filtering, logica para que lo que el usuario busque se guarde dentro del estado queries en la propiedad name para luego pasarle a la ruta get todas las queries necesarias

SearchBar en SortingAndFiltering

---

client/package.json
client/src/App.js
client/src/Components/NavBar/NavBar.jsx
client/src/Components/ProductCard/card.module.css
client/src/Pages/DataManagement.jsx
client/src/Pages/detail/detail.jsx
client/src/Pages/home/Home.jsx
client/src/Pages/home/home.module.css
client/src/Pages/sortingAndFiltering/sortingAndFiltering.jsx

- Se actualizó la libreria react error overlay 6.0.9.
- Se movió el grid de productos a la pestaña "products"
- Actualizaciones de estilos en Cards, Homepage, NavBar
- Se linkeó la tab Data Management entre el home y la Searchbar
- Se creó la carpeta home para agregar el file de estilos.
- Se linkeó la barra de busqueda a data management

Updates Home, Data Management, Searchbar, React library

---

api/index.js
api/src/controllers/putScoreController/PutScoreController.js
api/src/handlers/putScoreHandler/PutScoreHandler.js
api/src/middlewares/validateProducts/validatePostProduct.js
api/src/models/ProductsModel.js
api/src/routes/PutScoreRouter/PutScoreRouter.js
api/src/routes/index.js

Agregue las ruta score, tuve que modificar el model de products (cambie el score)

Backend-routeScore

---

api/index.js
api/src/controllers/productsController/GetProductByNameController.js
api/src/controllers/productsController/getProductByIdController.js
api/src/controllers/productsController/getProductsAll.js
api/src/controllers/productsController/postProductController.js
api/src/handlers/productsHandle/postProductHandler.js
api/src/helpers/cleanArrayProduct.js

Actualizacion de conexiones y relaciones entre tablas

Backend   update crud products add new relations

---

api/src/controllers/productsController/GetProductByNameController.js
api/src/handlers/productsHandle/getProductsHandler.js

Error al buscar un nombre que no existe

Backend fix get by name

---

api/src/controllers/productsController/deleteProductController.js
api/src/controllers/productsController/getProductByIdController.js
api/src/models/ProductsModel.js

Ya no se ven los Elementos borrados, al hacer peticiones con ids que ya existen, da un mensjae de error

Paranoid+ManagementWrongCalls

---

api/src/controllers/productsController/getProductsAdvanceController.js
api/src/controllers/productsController/postProductController.js
api/src/handlers/productsHandle/getProductsAdvanceHandler.js
api/src/helpers/filters/filterByCategories.js
api/src/helpers/filters/filterByTypes.js

ahora se puede hacer filtrado en muchos noveles de complejidad, mas de un type y mas de una categoria al mismo tiempo

update de busqueda avanzada

---

client/src/Components/Footer/Footer.module.css
client/src/Components/ProductCard/ProductCard.jsx
client/src/Pages/Login/Login.jsx
client/src/Pages/detail/detail.jsx
client/src/Pages/sortingAndFiltering/sortingAndFiltering.jsx

Se hicieron correcciones al filtrado y se agregó el link de login

Sorting and Filtering Updates

---

api/src/controllers/categoriesController/postCategoryController.js
api/src/controllers/ingredientController/postIngredientController.js
api/src/controllers/typesController/postTypeController.js
api/src/handlers/productsHandle/loadProductHandler.js
client/package.json

Se crea una ruta para poder pasar arrays de products,types,categories e ingredients en una sola request

CARGA DE DB

---

api/src/controllers/favTypesController/favTypesController.js
api/src/routes/FavTypesRouter/FavTypesRouter.js

Ahora devuelve productos aleatorios en caso de no recibir un id y si lo recibe devuelve los productos que incluyes los tipos favoritos del usuario

Cambio en el getFavTypes

---

client/src/Components/Carousel/carousel.jsx
client/src/Components/Paginated/paginated.jsx
client/src/Pages/home/Home.jsx

redirección de carousel, paginado y home

Redireccion

---

api/src/routes/ProductsRouter/ProductsRouter.js

fix update problem that delets a product wrongly

fix update

---

api/src/routes/ProductsRouter/ProductsRouter.js

mejora de ruta delete

---

api/src/controllers/rolesController/rolesController.js
api/src/controllers/userController/UserController.js
api/src/handlers/rolesHandler/RolesHandler.js
api/src/handlers/userHandler/UserHandler.js
api/src/routes/RolesRouter/RolRouter.js
api/src/routes/UserRouter/UserRouter.js

SE agregaron rutas para nuevo rol de adm, para cambiar la contraseña

Backend route rol auth

---

client/src/Pages/editCategoryTypeIngredient/editCategoryTypeIngredient.jsx

Updated Crud

---

client/src/App.js
client/src/Components/ModalMailing/ModalMailing.jsx
client/src/Components/ModalMailing/ModalMailing.module.css
client/src/Pages/crud_products/CrudProducts.jsx
client/src/Pages/editCategoryTypeIngredient/editCategoryTypeIngredient.jsx

Mailing funcionando, se envía un mail masivo , se puede poner objeto y asunto

Mailing Button

---

api/src/handlers/orderHandlers/createOrderHandler.js
api/src/middlewares/validateJwt/validateJwt.js
api/src/routes/PaymentRouter/PaymentRouter.js

Se agregó la validación con Jwt en la ruta de mercado pago
Se modificó para que desde la validación se obtenga el id

Backend router pay

---

api/src/controllers/orderControllers/createPaymentPreference.js
api/src/handlers/orderHandlers/paymentCryptoNotificationHandler.js
api/src/routes/PaymentRouter/PaymentRouter.js
client/src/App.js
client/src/Components/NavBar/NavBar.module.css
client/src/Components/Purchase/PaymentSelector.jsx
client/src/Components/Purchase/PendingPurchase.jsx
client/src/Components/Purchase/RejectedPurchase.jsx
client/src/Components/Purchase/SuccessPurchase.jsx

union de venta por cryptos a ventas consolidadas en DB, se empieza a menejar el front de la pasarela de pagos ya creado el carrito de compras

union de crypto a sales

---

client/src/Components/Cryptos/Cryptos.jsx

Se da por concluida la funcionalidad de generar una sale, y una order en DB desde el front

finalizacion de conexion de crypto y mp con sale de DB

---

api/src/controllers/authController/authController.js
api/src/handlers/userHandler/UserHandler.js

Backend prueba password

---

client/src/Pages/Login/Login.jsx

Al hacer login si encuentra el usuario se recibe el token

Login recibe el token

---

api/src/controllers/orderControllers/createPaymentPreference.js
client/src/Pages/NewUser/NewUser.jsx

las categorias favoritas eran un array, ahora son las categorias del back

fix register

---

api/src/controllers/orderControllers/createPaymentPreference.js
client/src/Components/Cryptos/Cryptos.jsx
client/src/Components/MercadoPagoTotal/MercadoPagoTotal.jsx
client/src/Components/Purchase/PaymentCrypto.jsx
client/src/Components/Purchase/PaymentSelector.jsx

para acceder a finalizar compra primero hay que estar loggeado

arreglo de comportamiento carrito

---

api/package.json
api/src/app.js
api/src/db.js

Deploy de la BD y Back en Render

DeployPrueba2

---

api/package.json
api/src/app.js
api/src/db.js

Eliminé los cambios hechos para hacer el deploy, se encuentra todo como en el estado antes del merge por deploy

Vuelta al E.Inicial

---

client/src/App.js
client/src/Components/Carousel/carousel.jsx
client/src/Components/Cryptos/Cryptos.jsx
client/src/Components/Footer/Footer.jsx
client/src/Components/IntegracionMercadoPago/IntegracionMercadoPago.jsx
client/src/Components/Maps/Maps.jsx
client/src/Components/MercadoPagoTotal/MercadoPagoTotal.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Components/Purchase/PaymentCrypto.jsx
client/src/Components/Purchase/PaymentSelector.jsx
client/src/Components/Purchase/PendingPurchase.jsx
client/src/Components/Purchase/RejectedPurchase.jsx
client/src/Components/Purchase/SuccessPurchase.jsx
client/src/Pages/about/about.jsx
client/src/Pages/carrito/carrito.jsx
client/src/Pages/carrito/carrito.module.css
client/src/Pages/detail/detail.jsx
client/src/Pages/detail/detail.module.css
client/src/assets/main.css

Todos los estilos de parte del usuario con tailwind

TailwindStyleUsers

---

client/src/Components/ProductCard/ProductCard.jsx
client/src/Pages/carrito/carrito.jsx
client/src/assets/main.css

Comente los botones de venta de mercado pago individual, ya que por ahora no funcionan

SuspendeMercadoPago

---

api/src/controllers/orderControllers/createPaymentPreference.js
api/src/handlers/productsHandle/getProductsAdvanceHandler.js
client/package.json
client/src/App.js
client/src/Components/Metrics/Metrics.jsx

Se deja en 12 productos por pagina

Front and back   completing sales

---

client/src/Pages/carrito/carrito.jsx
client/src/assets/main.css

AndaElCarrito

---

client/src/Components/Firebase.js
client/src/Components/Login/login.jsx
client/src/Components/Login/login.module.css
client/src/Pages/Login/Login.jsx
client/src/Pages/Login/Login.module.css

Login with FB

---

api/src/controllers/authController/authController.js
api/src/handlers/authHandler/authHandler.js
api/src/routes/AuthRouter/AuthRouter.js

Se creó la ruta a google desde el back

Front end components user

---

api/src/handlers/metricHandlers/getMonthPerformanceHandler.js
api/src/routes/MetricRouter/MetricRouter.js

Dicha Metrica lo que hace es, devolver un porcentaje tomando en cuenta el monto total de ventas del mes actual, con respecto al monto total de ventas del mes anterior

se agrega una nueva peticion de metrica

---

api/src/handlers/metricHandlers/getMonthPerformanceHandler.js

se incluye en desempeño anual, semestral junto al mensual

actualizacion de metrica

---

api/src/controllers/metricControllers/getSalesReport.js
api/src/handlers/metricHandlers/getAllSalesPaginatedHandler.js
api/src/routes/MetricRouter/MetricRouter.js

la ruta, http://localhost:3001/metric/all-sales, se le pasa un mes en numero, (el año es opcional por defecto sera el año actual) y devuelve las compras de ese mes o si no se pasa un mes, el historial completo de Sales, paginado

creacion de ruta get Sales

---

api/src/controllers/orderControllers/createPaymentPreference.js
client/src/Pages/carrito/carrito.jsx

se arregla el manejo de cantidad, de sumar y restar y de manejo de LocalStorage

arreglo de comportamiento de carrito

---

api/src/controllers/metricControllers/getOrdersReport.js
api/src/handlers/metricHandlers/getAllOrdersPaginatedHandler.js
api/src/routes/MetricRouter/MetricRouter.js
client/src/Components/ProductCard/ProductCard.jsx
client/src/Pages/home/Home.jsx

con esta nueva ruta se obtienen todas las orders con sus relaciones, paginada y ordenada.

creacion de ruta Orders

---

api/src/routes/UserRouter/UserRouter.js

Modificacion de rutas users

---

api/.gitignore
api/package.json
api/src/app.js
api/src/db.js

:) prueba_failed

---

api/src/controllers/userController/UserController.js

Se descomentó la ruta de detele

Se descomentó la ruta de delete

---

client/src/Pages/createProduct/CreateProduct.jsx
client/src/assets/main.css

Retoques Create Product

---

api/src/controllers/authController/authController.js
api/src/handlers/authHandler/authHandler.js
api/src/middlewares/authGoogle/authGoogle.js
client/src/Components/GoogleLogin/googleLogin.jsx

Solucion de bugs en el logueo a traves de terceros

Auth google fix de bugs
